language: android

before_install:
 - chmod +x gradlew
 - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
 - emulator -avd test -no-skin -no-audio -no-window &
 - adb wait-for-device
 - adb shell input keyevent 82 &

branches:
  only:
    - master

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-23

script:
    -./gradlew build connectedAndroidTest
    -./gradlew check